const Donor=require('../models/donorModel');
const {eligibilityFromDate,haversine,maskPhone}=require('../services/donorService');
const {clean}=require('../utils/sanitize');
const asyncHandler=require('../utils/asyncHandler');
const AppError=require('../utils/AppError');
function present(d,userLat,userLon){ const eligibility=eligibilityFromDate(d.last_donation_date,d.gender); const distance=haversine(userLat,userLon,d.latitude,d.longitude); return {donorId:d.donor_id,userId:d.user_id,name:d.name,gender:d.gender,bloodGroup:d.blood_group,age:d.age,weight:Number(d.weight),location:d.location,latitude:d.latitude===null?null:Number(d.latitude),longitude:d.longitude===null?null:Number(d.longitude),lastDonation:d.last_donation_date,isAvailable:Boolean(d.is_available),isEligible:eligibility.eligible,status:eligibility.status,remainingDays:eligibility.remainingDays,distanceKm:distance===null?null:Number(distance.toFixed(1)),maskedPhone:maskPhone(d.phone),profileImage:d.profile_image}; }
exports.list=asyncHandler(async(req,res)=>{ const filters={bloodGroup:req.query.bloodGroup,location:clean(req.query.location||''),available:req.query.available===undefined?undefined:req.query.available==='true'}; const rows=await Donor.list(filters); let data=rows.map(d=>present(d,req.query.lat,req.query.lon)); if(req.query.available==='true') data=data.filter(d=>d.isEligible); if(req.query.maxDistance) data=data.filter(d=>d.distanceKm!==null&&d.distanceKm<=Number(req.query.maxDistance)); res.json(data); });
exports.getOne=asyncHandler(async(req,res)=>{ const d=await Donor.findById(req.params.id); if(!d) throw new AppError('Donor not found',404); res.json({success:true,donor:present(d,req.query.lat,req.query.lon)}); });
exports.me=asyncHandler(async(req,res)=>{ const d=await Donor.findByUserId(req.user.user_id); res.json({success:true,donor:d?present(d):null}); });
exports.become=asyncHandler(async(req,res)=>{ if(await Donor.findByUserId(req.user.user_id)) throw new AppError('You are already registered as a donor',409); const data=clean(req.body); if(!data.bloodGroup||!data.age||!data.weight||!data.location) throw new AppError('Blood group, age, weight and location are required',422); if(Number(data.age)<18||Number(data.age)>65||Number(data.weight)<50) throw new AppError('Donor eligibility requires age 18-65 and weight at least 50 kg',422); const id=await Donor.create({userId:req.user.user_id,bloodGroup:data.bloodGroup,age:Number(data.age),weight:Number(data.weight),location:data.location,latitude:data.latitude,longitude:data.longitude,lastDonation:data.lastDonation}); res.status(201).json({success:true,message:'Donor profile created',donorId:id}); });
exports.availability=asyncHandler(async(req,res)=>{ if(typeof req.body.isAvailable!=='boolean') throw new AppError('isAvailable must be true or false',422); if(!await Donor.findByUserId(req.user.user_id)) throw new AppError('Donor profile not found',404); const d=await Donor.updateAvailability(req.user.user_id,req.body.isAvailable); res.json({success:true,message:'Availability updated',donor:present(d)}); });
exports.lastDonation=asyncHandler(async(req,res)=>{ if(!await Donor.findByUserId(req.user.user_id)) throw new AppError('Donor profile not found',404); const d=await Donor.updateLastDonation(req.user.user_id,req.body.lastDonation||null); res.json({success:true,message:'Last donation date updated',donor:present(d)}); });
exports.contact=asyncHandler(async(req,res)=>{ const d=await Donor.findById(req.params.id); if(!d) throw new AppError('Donor not found',404); res.json({success:true,donorId:d.donor_id,name:d.name,phone:d.phone}); });
